name: CI/CD FastAPI App

on:
push:
branches: [ "main" ]

jobs:
build-and-deploy:
runs-on: ubuntu-latest

steps:
- name: Checkout code
  uses: actions/checkout@v4

# 🔧 Enable buildx
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3

# 🔐 Login to Docker Hub
- name: Login to Docker Hub
  uses: docker/login-action@v3
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

# 🏗️ Build + push (IMPORTANT PART)
- name: Build and push image
  uses: docker/build-push-action@v5
  with:
    context: .
    push: true
    tags: achin43/rep:latest
    platforms: linux/amd64

# 🚀 Deploy to VM
- name: Deploy via SSH
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.VM_HOST }}
    username: ${{ secrets.VM_USER }}
    key: ${{ secrets.VM_SSH_KEY }}
    script: |
      docker pull achin43/rep:latest
      docker stop my-app || true
      docker rm my-app || true
      docker run -d -p 8000:8000 --name my-app achin43/rep:latest
